# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import semantic_search_server_pb2 as semantic__search__server__pb2


class SemanticSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_semantic_search_result = channel.unary_unary(
                '/SemanticSearch/get_semantic_search_result',
                request_serializer=semantic__search__server__pb2.Phrase.SerializeToString,
                response_deserializer=semantic__search__server__pb2.Phrase.FromString,
                )


class SemanticSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_semantic_search_result(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_semantic_search_result': grpc.unary_unary_rpc_method_handler(
                    servicer.get_semantic_search_result,
                    request_deserializer=semantic__search__server__pb2.Phrase.FromString,
                    response_serializer=semantic__search__server__pb2.Phrase.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SemanticSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SemanticSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_semantic_search_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SemanticSearch/get_semantic_search_result',
            semantic__search__server__pb2.Phrase.SerializeToString,
            semantic__search__server__pb2.Phrase.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
